### PR TITLE
add: npmignore

### PR DESCRIPTION
**Pull request by zhuangya**

### CODE REVIEW

**Comment by bahmutov** [comment]
I would go the whitelist mode using "files" list in package.json, see https://glebbahmutov.com/blog/smaller-published-NPM-modules/

**Comment by VictorBjelkholm** [comment]
Yeah, I agree with @bahmutov, whitelisting would be better so we don't always have to change which files to exclude, when adding more.

**Comment by zhuangya** [comment]
@bahmutov thanks for the very useful article and now i've changed to "whitelist" mode

@VictorBjelkholm could you please check the path if i didn't anything wrong?

thanks.

**Comment by zhuangya** [comment]
also, pkgfiles repot:

BEFORE:

```
PATH                                                SIZE       %
.npmignore                                          0 B        0%
.dockerignore                                       28 B       0%
example_project/test.js                             164 B      0%
example_project_with_DockerTemplate/test.js         164 B      0%
example_project_with_DockerTemplate/DockerTemplate  170 B      0%
example_project_with_DockerTemplate/package.json    280 B      0%
example_project/package.json                        280 B      0%
package.json                                        865 B      0%
readme.md                                           4.34 kB    0%
index.js                                            5.73 kB    0%
index.html                                          5.87 kB    0%
cli.js                                              6.63 kB    0%
test/core_test.js                                   6.9 kB     0%
example_2.gif                                       36.72 kB   2%
example_3.gif                                       89.59 kB   5%
example_1.gif                                       243.66 kB  13%
demo.gif                                            691.63 kB  37%
example_4.gif                                       755.51 kB  41%

DIR                                                 SIZE       %
example_project/                                    444 B      0%
example_project_with_DockerTemplate/                614 B      0%
test/                                               6.9 kB     0%
.                                                   1.85 MB    100%

PKGFILES SUMMARY
Size on Disk with Dependencies  ~5.88 MB
Size with Dependencies          ~5.72 MB
Publishable Size                ~1.85 MB
Number of Directories           4
Number of Files                 18
```


AFTER

```
PATH           SIZE      %
.dockerignore  28 B      0%
package.json   933 B     5%
readme.md      4.34 kB   25%
index.js       5.73 kB   32%
cli.js         6.63 kB   38%

DIR            SIZE      %
.              17.65 kB  100%

PKGFILES SUMMARY
Size on Disk with Dependencies  ~5.91 MB
Size with Dependencies          ~5.72 MB
Publishable Size                ~17.65 kB
Number of Directories           1
Number of Files                 5
```

**Comment by VictorBjelkholm** [comment]
Awesome! Thanks a lot for this @zhuangya! 👍

**Pull request merged**
