### PR TITLE
Preventing crash on error

### PR DESCRIPTION
**Pull request by bahmutov**
I noticed in some of my projects `autochecker` was crashing (I added printing chunks in the output below)
```
fatal: Not a git repository (or any of the parent directories): .git
Could not find git repo in /usr/src/app/node_modules/.git
data <Buffer 7b 22 73 74 72 65 61 6d 22 3a 22 67 69 74 2d 69 73 73 75 65 73 40 31 2e 32 2e 30 20 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 67 69 74 2d 69 73 73 75 65 ... >
parsed chunks []
/Users/gleb/.nvm/versions/node/v6.0.0/lib/node_modules/autochecker/index.js:123
        if (chunks[chunks.length - 1].error) {
                                     ^
TypeError: Cannot read property 'error' of undefined
```
since the chunks were an empty array, checking if last chunk has an error causes a crash.

### CODE REVIEW

**Comment by bahmutov** [comment]
interesting - not sure where the crash on CI is coming from

**Comment by bahmutov** [comment]
Victor, any intention to merge this safe guard?

**Comment by bahmutov** [comment]
This problem exists right now - when cloning this repo from HEAD and running `npm install` inside it crashes exactly in this spot
```sh
$ npm i
> autochecker@0.9.1 prepublish /Users/me/git/autochecker
> ./cli.js 4.4.2 5.10.1 6.0.0
autochecker Running tests in 3 different sessions | Path: /Users/me/git/autochecker
4.4.2	- building image
5.10.1	- building image
6.0.0	- building image
/Users/me/git/autochecker/index.js:121
        if (chunks[chunks.length - 1].error) {
                                     ^

TypeError: Cannot read property 'error' of undefined
    at IncomingMessage.stream.on (/Users/me/git/autochecker/index.js:121:38)
```
this pull request fixes this crash

**Comment by VictorBjelkholm** [comment]
@bahmutov Hey, sorry for missing this and thanks a lot for the fix! Will get around to do a release in a couple of minutes.

**Pull request merged**
